addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - golang
      - python3
      - clang

install:
  - pip3 install cpplint
  - go get github.com/golang/lint/golint
  - go install github.com/golang/lint/golint
  - pip3 install yapf
  - pip3 install pylint

script:
  - ./.travis.sh
